[package]
name = "voyager_client"
version = "0.1.4"
edition = "2021"
description = "Client for interacting with NASA's Open APIs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
pbr = "1.0.4"
serde = "1.0.131"
serde_derive = "1.0.131"
serde_json = "1.0.73"
ureq = "2.3.1"
users = "0.11.0"
