[package]
name = "voyager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fstrings = "0.2.3"
serde = "1.0.131"
serde_derive = "1.0.131"
serde_json = "1.0.73"
ureq = "2.3.1"
users = "0.11.0"
